### ISSUE TITLE
NullPointerException wenn das Spielfeld voll ist

### ISSUE THREAD

**Issue by mmitch** [fiduciagad/connected-n#19]
Wenn die Clients eine Partie spielen, bei der sie das ganze Feld voller Steine schaufeln, stürzt der Server reproduzierbar ab:

```
Exception in thread "Thread-0" java.lang.NullPointerException
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.ase.fourwins.udp.server.UdpServer$UdpPlayer.gameEnded(UdpServer.java:164)
        at org.ase.fourwins.game.DefaultGame.lambda$runGame$2(DefaultGame.java:147)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
        at org.ase.fourwins.game.DefaultGame.runGame(DefaultGame.java:147)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:442)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
```

Es fehlt wohl eine Abbruchbedingung „Spielfeld voll, unentschieden“.

Der konkrete Verlauf dieses Spiels war dieser:

```
0 0 0 1 0 0 0
0 0 0 2 0 0 0
0 0 0 2 1 0 0
0 0 0 2 1 1 0
0 0 0 3 1 1 0
0 1 0 3 1 1 0
0 1 0 3 1 2 0
1 1 0 3 1 2 0
1 1 0 3 1 2 1
1 1 0 3 1 3 1
1 1 0 3 2 3 1
2 1 0 3 2 3 1
3 1 0 3 2 3 1
3 2 0 3 2 3 1
3 2 0 3 2 3 2
3 2 0 4 2 3 2
3 2 0 4 2 4 2
3 2 0 4 3 4 2
3 2 0 5 3 4 2
3 2 0 5 3 4 3
3 2 0 6 3 4 3
3 2 0 6 4 4 3
4 2 0 6 4 4 3
4 3 0 6 4 4 3
4 3 1 6 4 4 3
4 3 1 6 5 4 3
4 3 2 6 5 4 3
5 3 2 6 5 4 3
5 3 3 6 5 4 3
5 3 4 6 5 4 3
5 4 4 6 5 4 3
5 4 4 6 5 4 4
6 4 4 6 5 4 4
6 4 5 6 5 4 4
6 4 5 6 6 4 4
6 4 5 6 6 5 4
6 4 5 6 6 6 4
6 5 5 6 6 6 4
6 5 5 6 6 6 5
6 5 6 6 6 6 5
6 6 6 6 6 6 5
6 6 6 6 6 6 6
```

Das ist von oben nach unten zu lesen: Jede Zeile ist ein Zug und enthält die Höhen der einzelnen Spalten:

- `0 0 0 1 0 0 0`: erster Zug in die Mitte
- `0 0 0 2 0 0 0`: zweiter Zug obendrauf
- `0 0 0 2 1 0 0`: dritter Zug rechts daneben
- …
- `6 6 6 6 6 6 6`: alle Spalten bis oben gefüllt

**Comment by pfichtner** [comment]
Ohne in den Code zu schauen habe ich eine Ahnung woran es liegen könnte. 
Das ist tatsächlich etwas, was mir von Anfang an weh tat, dass es keine Tests gibt, bei denen das Board vollgeschaufelt wird (was leider eben nicht ganz so trivial ist).

**Comment by pfichtner** [comment]
Wir lagen beide mit unserer Annahme falsch, das die Partie zu Ende wird duchaus erkannt: 
```at org.ase.fourwins.udp.server.UdpServer$UdpPlayer.**gameEnded(**UdpServer.java:164)```

Ich schau mal an was es liegt

**Comment by pfichtner** [comment]
Ok, Fehler sollte klar sein: https://github.com/fiduciagad/connected-n/blob/cd090ab336e6cf8850d9dedeaefc884cf7422719/udp/src/main/java/org/ase/fourwins/udp/server/UdpServer.java#L163
Im Fall vom DRAW ist der Token null. Ich werde es fixen, sobald ich einen roten Test dafür habe. 
Falls Du lokal temporär fixen möchtest: ```state.getScore()``` -> ```state.getScore() == null ? "" : state.getScore()```

**Comment by pfichtner** [comment]
@FrankR85 Um den Issue fixen zu können müssen wir die definieren, wie die Nachricht im DRAW Fall aussehen soll
```RESULT;ergebnis;spieler_name;grund```

Was soll ```spieler_name``` sein? Leer oder der Spieler der den letzten Stein eingeworfen hat? Ich plädiere klar zu leer.

**Comment by FrankR85** [comment]
Ja, wäre am plausibelsten, müsste man dann nur in der ```Readme``` als Sonderfall ergänzen.

**Comment by FrankR85** [comment]
Ich bin gerade aus anderen Gründen über die gleiche Stelle gestolpert und finde das Protokoll bei ```RESULT``` generell ungünstig.

Meines Erachtens sollte ```ergebnis```die Ausprägungen ```FIRST_PLAYER_WINS; SECOND_PLAYER_WINS; DRAW``` haben. Dann bräuchte man ```spieler_namen``` auch nicht.

Ich finde, das Protokoll ist einfacher, wenn wir nicht zwischen ```Spieler 1 gewinnt``` und ```Spieler 2 verliert``` unterscheiden.

**Comment by pfichtner** [comment]
Die NPE sollte erstmal weg sein (statt einer NPE wird dann null als Token ausgegeben). Das ist nur temporär. Ich ergänze noch die Tests, welche das Verhalten des UdpPlayers in den drei Fällen beschreiben. 
Wir können die LOSE Meldung zu einer negierten WIN Meldung vereinheitlichen. Mit FIRST und SECOND wären nicht mehr n Spieler möglich (was derzeit prinzipiell möglich ist).

**Comment by pfichtner** [comment]
Die NPE ist nachweislich weg, Tests hinzugefügt, welche den Status Quo(!) testen (jetzt können wir den ändern)

`RESULT;WIN;winnerName;FOUR_IN_A_ROW`
https://github.com/fiduciagad/connected-n/blob/98d63423d5ead64604b24036aa381d5289c0877e/udp/src/test/java/org/ase/fourwins/udp/server/UdpServerTest.java#L308

`RESULT;LOSE;loserName;ILLEGAL_COLUMN_ANNOUNCED`
https://github.com/fiduciagad/connected-n/blob/98d63423d5ead64604b24036aa381d5289c0877e/udp/src/test/java/org/ase/fourwins/udp/server/UdpServerTest.java#L316

`RESULT;DRAW;null;`
https://github.com/fiduciagad/connected-n/blob/98d63423d5ead64604b24036aa381d5289c0877e/udp/src/test/java/org/ase/fourwins/udp/server/UdpServerTest.java#L324

**Comment by pfichtner** [comment]
@FrankR85 Wenn wir aus LOSE eine negierte WIN Situation nach aussen machen wollten, dann würde ich das vermutlich auch im inneren auflösen. 
Ich finde es eigentlich gar nicht so schlecht, wenn das Protokoll vielleicht nicht 1000% super ist, das ist in der Realität ja auch mal so, dass man als Client was umbiegen muss. 

Ich schliesen diesen Issue, da die NPE behoben ist und mit 32359d3ca339d7ff0be6aa3df21004a27f5f6d90 der Server sich so verhält wie er sich m.E. verhalten soll. @FrankR85 @mmitch falls das jetztige VErhalten für euch nicht ok ist, bitte entsprechend kommentieren oder den Issue wieder eröffnen oder einen neuen aufmachen.

**Comment by mmitch** [comment]
Klingt gut und sieht gut aus!

FIRST_PLAYER/SECOND_PLAYER hätte ich ungerne im Protokoll, ichwill  im Client gar nicht mitzählen, wer gerade dran ist (muss ich vermutlich trotzdem, aber das ist meine eigene Schuld ;-)
Die Frage „Könnte man nicht auch mit mehr als 2 Leuten spielen?“ habe ich mir letzte Woche auch gestellt – cool, dass das prinzipiell geht.
