### ISSUE TITLE
Verbindungsprobleme mit manchen Sprachen

### ISSUE THREAD

**Issue by pfichtner** [fiduciagad/connected-n#32]
Nicht alle Teilnehmer der Codingchallenges schaffen es, mit dem Server zu kommunizieren. 
Funktionierend: 
- Java (Linux)
- Java (MacOS)
- Java (Windows)
- Typescript (Linux)

Nicht funktionierend: 
- Typescript (Linux)
- Swift (MacOS)
- Python (Windows)

Das Problem war jeweils, dass Pakete am Server ankamen, die Antwortpakete aber nicht bei den Bots. Ein Versuchsaufbau mit netcat auf den probelmatischen Rechnern hat ergeben, dass die jeweiligen problematischen Sprachen nicht mit dem UdpServer, aber mit einem `netcat -u -l 4446` Server kommunzieren konnten. Mitschnitte per wireshark ergaben, dass bei netcat der Sourceport der Antwortpakete 4446 war, beim UdpServer hingegen ein zufälliger Port. Das liegt daran, dass der UdpServer beim Senden der Antwortpakete einen neues Socket nutzt. Eine temporäres Ändern dieses Verhaltens führte zum Erfolg.

**Comment by pfichtner** [comment]
Mit #33 korrigiert. Warum es mit manchen Sprachen funktioniert und mit anderen nicht ist mir allerdings nicht ganz klar.

**Comment by mmitch** [comment]
Wenn ich das richtig überfliege, benutzt der Server jetzt ein- und ausgehend den gleichen Port.

"Antwortpaket des Serviers kommt von einem anderen Port" war genau der Grund, warum die UDP-Kommunikation aus der Bash nicht funktioniert hat und ich mir nach viel Gefrickel den Perl-Wrapper schreiben musste.
Ich schaue die Tage mal, ob das jetzt auch einfacher wird.

**Comment by pfichtner** [comment]
@mmitch das hatte ich auch vermutet und wollte DIch darauf noch hinweisen. 
Bin gespannt, ob das Problem dadruch behoben wird!

**Comment by mmitch** [comment]
Bin jetzt endlich mal zum Testen gekommen:
Seit Commit 4f6ce6e47529342be6e0ae452b827a80cbfe69ba funktioniert gar nichts mehr …
Der frisch gestartete Server wirft ca. alle 250ms eine SocketTimeoutException, das sieht inklusive Start so aus:

```
Starting server
Listening on 4446
Tournament starting
java.net.SocketTimeoutException: Receive timed out
        at java.base/java.net.PlainDatagramSocketImpl.receive0(Native Method)
        at java.base/java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:181)
        at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:814)
        at org.ase.fourwins.udp.server.UdpServer.startServer(UdpServer.java:259)
        at org.ase.fourwins.udp.server.Main.doMain(Main.java:88)
        at org.ase.fourwins.udp.server.Main.main(Main.java:73)
java.net.SocketTimeoutException: Receive timed out
        at java.base/java.net.PlainDatagramSocketImpl.receive0(Native Method)
        at java.base/java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:181)
        at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:814)
        at org.ase.fourwins.udp.server.UdpServer.startServer(UdpServer.java:259)
        at org.ase.fourwins.udp.server.Main.doMain(Main.java:88)
        at org.ase.fourwins.udp.server.Main.main(Main.java:73)
java.net.SocketTimeoutException: Receive timed out
        at java.base/java.net.PlainDatagramSocketImpl.receive0(Native Method)
        at java.base/java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:181)
        at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:814)
        at org.ase.fourwins.udp.server.UdpServer.startServer(UdpServer.java:259)
        at org.ase.fourwins.udp.server.Main.doMain(Main.java:88)
        at org.ase.fourwins.udp.server.Main.main(Main.java:73)
```

Gebaut habe ich mit `mvn -DskipTests package` und starten tue ich mit `java -cp ./udp/target/classes:./core/target/classes org.ase.fourwins.udp.server.Main`.
Die Tests skippe ich normalerweise, weil das Tournament hier auf dem langsamen Rechner ewig dauert. Jetzt merke ich gerade, dass die Tests fehlschlagen. Da mache ich mal eine Issue zu auf, weil ich nicht verstehe, warum das fehlschlägt.  Das, was ich sonst noch so getippt habe, lasse ich mal hier stehen – der zweite Punkt aus der Aufzählung gilt unabhängig von einem eventuellen Problem im Server.

Die Anmeldung der Clients kommt durch, aber bereits das Joinen auf die Season klappt nicht mehr und der Server sagt "weg mit dem Client, zu viele Timeouts".
Dabei sind das noch die unveränderten Clients mit meinem UDP-Wrapper. Mit dem Vorgängercommit funktioniert alles noch.

Ich bin deshalb nicht dazu gekommen, "nackiges" UDP per Bash zu testen, aber das kann auch gar nicht funktionieren, weil es ja zwei Probleme gibt:

1. Quell- und Zielport des Servers sind unterschiedlich – das könnte sich verbessert haben
2. Das Protokoll ist nicht zeilenbasiert und hat auch kein erkennbares Trennzeichen am Ende einer Nachricht. Man braucht die Metainformationen "was ist ein UDP-Paket", um das Protokoll zu sprechen, es klappt nicht, wenn man nur den Bytestrom ohne Trenner hat. Da die Bash ohne Hilfsmittel nur zeilen- oder zeichenweise lesen könnte und die UDP-Pakete gar nicht sieht, kann das ohne den udp-Wrapper nicht funktionieren. Der macht nämlich nicht nur die Port-Geschichte, sondern mappt auch zwischen Paketen und Textzeilen, wie mir jetzt wieder eingefallen ist.
